name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Continuous Integration
        run: |
          yarn
          yarn bootstrap
          yarn build
          yarn lint
          yarn test

      - name: Continuous Deployment
        run: |
          yarn
          yarn deploy:storybook --ci
